name: Release

# Controls when the workflow will run
on:
  pull_request_review:
    types: [submitted]
    branches: ['master']
    #paths: [' **path/**']
jobs:
  checkout:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2    

  promote-RC-version:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - name: promote-RC-version
        run: echo promote-RC-version
        
  deploy-to-PRO:
    needs: promote-RC-version
    runs-on: ubuntu-latest

    steps:
      - name: deploy-to-PRO
        run: echo Deploy to PRO    
        
  tests:
    needs: deploy-to-PRO
    runs-on: ubuntu-latest

    steps:
      - name: tests
        run: echo Running tests    
        
  post:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: post
        run: echo Running post actions        
