name: Snapshot

# Controls when the workflow will run
on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
        
  build:
    #needs: [static-analysis, unit-tests]
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      
      - run: mkdir -p ${{github.workspace}}/newFolder
      - run: echo hello > ${{github.workspace}}/newFolder/world.txt
      - run: ls ${{github.workspace}}/newFolder

       
